### ISSUE TITLE
vector display after pointcloud

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#176]
On results panel, if you don't view pointcloud before viewing vectors, then the vectors do not display correctly

![Image](https://user-images.githubusercontent.com/60604372/211597275-14276c37-0c42-424b-8200-0458f9499b62.png)

**Comment by lauramurgatroyd** [comment]
- Remove "View pointcloud/vectors" button - should auto update when dropdown changed
- "View vectors" should be replaced with "View:"
- Options underneath view vectors should not be clickable if "View pointcloud" is selected
- Have separate section for viewing vectors and vector settings

**Comment by paskino** [comment]
Also, subvolume size and points in subvolume are needed to define which run to display the vectors/pointcloud for, so I would move them below the select a run.

**Comment by paskino** [comment]
Maybe this is not a bug any longer. I have not seen it for long.

**Comment by DanicaSTFC** [comment]
(Edo and I can't reproduce this bug). 

This seems to be something related to the fact that the viewer was not updated before #270 .  An issue similar to this is https://github.com/TomographicImaging/iDVC/issues/177 where not all points are listed in the widget "points in point cloud". This can happen between different runs or even different Views, the points can be "0" and no vectors are shown in the viewer. It seems that the vectors are not shown because the "vector range" widgets are not updated correctly.
