### ISSUE TITLE
Numbers of Degrees of Freedom

### ISSUE THREAD

**Issue by grzesiek12001** [TomographicImaging/iDVC#234]
Dear Creators,

Thank you for releasing your program. Currently, I am trying to use it for my doctoral research. I am using version 22.3.0. In the 'Run DVC' tab, no matter what value I choose for Numbers of Degrees of Freedom, the analysis is always computed for a value of '3'. Has anyone encountered such a result? Do you have any ideas on what I can do? Thank you for your assistance!

**Comment by DanicaSTFC** [comment]
Hi,

Thank you for your contribution. We are happy to know you are using our iDVC software in your research. We are looking into the issue you reported. Could you give us more information on why you think the number of degrees of freedom is fixed to 3?

Please not we are about to release v24.0.0 next month. This will be followed by a workshop at the "dxct" conference: https://dxct.co.uk/training-day/ Our training is under "CCPi" and is shown on the right hand side. If you have the chance, please register!

**Comment by grzesiek12001** [comment]
Perhaps I misunderstood something from the instructions, but if I set Numbers of Degrees of Freedom to 12, should I receive information about deformation and rotation in the .disp file? I set the analysis settings to 12, yet I only receive results for displacements. Below are screenshots of the analysis settings and the .disp file.

https://aghedupl-my.sharepoint.com/:i:/g/personal/kaczmarc_agh_edu_pl/EdYHxmeom5RPpVfc1pTI1I4BnhGglzKBnEKXwBWqZuKd1w?e=tbklIO

https://aghedupl-my.sharepoint.com/:i:/g/personal/kaczmarc_agh_edu_pl/ETLA-UO_agxMjo1SaTNC580B5CXHI4qM4pfdrtoCIQZboA?e=EGjrYD

Thank you for your assistance.

**Comment by DanicaSTFC** [comment]
Thank you for your feedback and extra information. My colleagues and I are currently looking into this and will get back to you.

**Comment by paskino** [comment]
Hi @grzesiek12001 

We checked with @BrianBay and the output for 6 and 12 optimization parameters is truncated down the first 3. In general, 6 and 12 are used to improve the accuracy of the displacement output (the first 3 parameters) but are not used directly themselves. But there are cases where it is useful to have that output.

We should introduce the terminology “number of optimization parameters” instead of degrees of freedom to make that clear.
- #236 

If required we can output the full optimization parameter vector (3, 6, or 12 numbers for each point).

Do you need the other parameters?

**Comment by DanicaSTFC** [comment]
We are glad the explanation helped. We will address your concerns in our future release of the software. I will close this issue.  If you need to contact us again do not hesitate to open a new issue or send us an email. Best, Danica
